# conf/default.yaml
name: ???  # 新增：自动生成实验名
expname: ${name}  # 保持向后兼容

# metadata specialised for each experiment
core:
  version: 0.0.1
  tags:
    - ${now:%Y-%m-%d}

hydra:
  job:
    chdir: false  # 修改：不切换到输出目录，避免嵌套
    env_set:
      WANDB_DIR: ${oc.env:WABDB_DIR}
      
  run:
    dir: outputs/${name}/${now:%m-%d-%H-%M-%S}  # 修改：新的目录结构

  sweep:
    dir: outputs/${now:%Y-%m-%d}/sweep-${name}  # 修改：sweep 目录
    subdir: ${hydra.job.num}

defaults:
  - _self_
  - data: ???
  - logging: default
  - model: vae
  - optim: default
  - train: multi_gpu.yaml

# 新增：恢复训练相关配置
resume_from: null  # 可以指定其他运行的路径来恢复训练l